api_version = "2026-04"

[[extensions]]
name = "CurtainsUK OpenAI Ads"
handle = "curtainsuk-openai-ads"
type = "web_pixel_extension"
runtime_context = "strict"

[extensions.customer_privacy]
analytics = true
marketing = true
preferences = false
sale_of_data = "disabled"

[extensions.settings]
type = "object"

[extensions.settings.fields.pixelId]
name = "OpenAI Ads Pixel ID"
description = "Pixel ID for the CurtainsUK Website data source."
type = "single_line_text_field"
validations = [
  { name = "min", value = "1" }
]
