# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d18f79c0a0d1db2df7babeb26906443e"
name = "curtains-uk-mtm"
application_url = "https://curtainsuk-staging-gateway.vercel.app"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://curtainsuk-staging-gateway.vercel.app/api/shopify/auth/callback" ]

[app_proxy]
url = "https://curtainsuk-staging-gateway.vercel.app/api/staging/shopify-proxy"
subpath = "curtainsuk-decision"
prefix = "apps"
