export const version = 'customer-trust-v1-review-2026-09-21';
export const contacts = { support:'support@curtainsuk.com', complaints:'complaints@curtainsuk.com', media:'media@curtainsuk.com', changes:'enquiries@curtainsuk.com' };
export const changeNotice = 'Need to request a change? Email us within 2 hours of placing your order at enquiries@curtainsuk.com. We’ll review your request and get in touch.';
export const imageNotice = 'Adding an image is optional. We use your room or reference image only to provide the Fabric Intelligence service you request, with automated image analysis to suggest colours and fabric directions. We do not use uploaded room images for model training, general AI training, product or model improvement, unrelated evaluation or research, marketing, or a reusable image dataset. Please leave people, addresses, documents and other personal details out of the picture. Our current consultation persistence path stores derived colour and preference records rather than raw image data; the upstream processor, temporary handling, logs and deletion arrangements are being technically verified. Read Room Image & AI Privacy before uploading.';
export const groups = [
  ['CurtainsUK', [['About Us','/pages/about-us-1'],['Fabric Intelligence™','/apps/curtainsuk-decision/consultation?experience=premium&entry=match'],['Browse Fabrics','/pages/fabric-library?view=browse-fabrics'],['Curtain Style','/pages/fabric-library?view=curtain-style'],['Shop by Window','/pages/solve-my-window'],['Inspiration / Gallery','/#curtainsuk-inspiration'],['Media & Press','/pages/media'],['Sitemap','/pages/sitemap']]],
  ['Help & Customer Care', [['Guided Measure','/pages/how-to-measure'],['How to Fit','/pages/how-to-fit'],['Fabric Samples','/pages/samples'],['Delivery Information','/policies/shipping-policy'],['Curtain Care & Cleaning','/pages/fabric-care-guide'],['FAQs','/pages/faq-1'],['Contact Us','/pages/contact-us'],['Complaints','/pages/complaints'],['Your made-to-measure order','/pages/made-to-measure-orders']]],
  ['Responsible Business', [['Responsible Sourcing','/pages/responsible-sourcing'],['Modern Slavery & Supply Chain','/pages/modern-slavery-supply-chain'],['Equality, Diversity & Non-Discrimination','/pages/equality-diversity'],['Recycling & Waste','/pages/recycling-waste']]],
  ['Legal & Privacy', [['Terms & Conditions','/policies/terms-of-service'],['Privacy Policy','/policies/privacy-policy'],['Cookie Information','/pages/cookies-policy'],['Refunds & Returns','/policies/refund-policy'],['Fabric Colour, Shade & Variation','/pages/curtain-fabric-colour-guide'],['Room Image & AI Privacy','/pages/room-image-ai-privacy'],['Website Accessibility','/pages/accessibility'],['Cookie Settings','#cookie-settings']]],
];
const link = (href,text) => `<a href="${href}">${text}</a>`;
const support = link('mailto:'+contacts.support, contacts.support);
const complaints = link('mailto:'+contacts.complaints, contacts.complaints);
const colour = link('/pages/curtain-fabric-colour-guide','Fabric Colour, Shade & Variation');
const returns = link('/policies/refund-policy','Refunds & Returns');
const privacy = link('/policies/privacy-policy','Privacy Policy');
const company = '<p>Apex Curtains Ltd trading as Curtains UK. Company number 15652466 (England and Wales).</p><p>Customer correspondence and authorised returns address: 36–44 Bolton Road, Blackburn, BB2 3FA.</p>';
const page = (key,title,url,action,sections,confirmations=[]) => ({key,title,url,action,sections,confirmations,status:confirmations.length?'NEEDS CONFIRMATION':'READY FOR OWNER REVIEW'});
export const pages = [
  page('refund-policy','Refunds & Returns','/policies/refund-policy','REWRITE',[
    ['Made to your specification','Our made-to-measure curtains are made to your individual choices and measurements. The usual online change-of-mind cancellation right does not apply to goods made to your specifications or clearly personalised. A change of mind alone does not normally entitle you to return them. This does not remove your rights if goods are faulty, damaged, incorrect or materially not as described.'],
    ['Requesting a change',changeNotice+' This is a request window, not a statutory cancellation period or a promise that a change can be made. Please give your order number and the change you would like. We will review the request; changes may not be possible once processing or manufacture has begun.'],
    ['Fabric samples','Fabric samples are separate from your made-to-measure curtains. We do not offer a voluntary change-of-mind return or refund for samples. This does not remove your rights where a sample is faulty, damaged, incorrect or materially not as described. Contact '+support+' with your order details and useful photographs where appropriate.'],
    ['Faulty, damaged or incorrect goods','Contact '+support+' with your order number, a description of the problem and photographs if useful and possible. We may need to inspect the goods. Your legal remedies depend on the circumstances and may include a refund, repair or replacement. We do not impose a short reporting deadline that removes your statutory rights.'],
    ['Refunds and return costs','Where a remedy is due, we will work with you on the appropriate repair, replacement or refund and normally use the original payment method. We do not impose an invented reporting deadline that removes statutory rights.'],
    ['Colour and finish','Please read '+colour+' and consider a physical sample before ordering. Normal material characteristics do not give us permission to supply the wrong fabric or goods materially different from their description.'],
    ['Further help','If you are unhappy with how a return is handled, see '+link('/pages/complaints','Complaints')+'. Your statutory rights are unaffected.'],
  ]),
  page('terms-of-service','Terms & Conditions','/policies/terms-of-service','REWRITE',[
    ['Who you are buying from',company+'<p>For help before or after ordering, contact '+support+'.</p>'],
    ['Choosing fabric and curtains','Our service helps you choose fabrics, order samples and configure made-to-measure curtains. Fabric Intelligence and Curtain Anatomy are aids to choosing: the neutral Anatomy studies are not exact previews of a purchasable fabric. Read '+colour+' and check the fabric identity and specification before ordering.'],
    ['Measurements','Follow '+link('/pages/how-to-measure','Guided Measure')+' using fitted hardware. Supply the raw width and drop requested for your setup. CurtainsUK applies the relevant workshop calculations later. Do not add heading, hook or fullness allowances yourself. If unsure, ask us before placing an order. Our review does not replace an on-site measurement service.'],
    ['Checking your configuration','Check fabric, opening, hardware, heading, width, drop, lining and pair/single choices before continuing. A validated made-to-measure item is fixed in Shopify. To change it, remove it and configure your curtains again; the replacement is priced and checked afresh.'],
    ['Price, payment and availability','Check the goods price, VAT treatment, delivery charge and total presented before payment. The made-to-measure service recalculates the price and checks current fabric eligibility and stock before creating checkout. If a supply problem arises after payment, CurtainsUK will contact you about the available resolution. We will not substitute a different fabric without your agreement.'],
    ['After you order','Payment sends your made-to-measure order to CurtainsUK review. It does not automatically approve manufacture or release it to the workroom. See '+link('/pages/made-to-measure-orders','Your made-to-measure order')+' for the steps.'],
    ['Workmanship','CurtainsUK strives for high standards of workmanship. Where a genuine workmanship or manufacturing defect is identified, we will work with you to rectify and resolve the issue appropriately. We do not offer a fixed-duration warranty in this notice; statutory rights remain unaffected.'],
    ['Changes, cancellation and problems',changeNotice+' Requested changes are subject to review and are not guaranteed. See '+returns+' for the distinction between made-to-measure goods, samples and goods that are faulty or not as described.'],
    ['Delivery','Read '+link('/policies/shipping-policy','Delivery Information')+' and the delivery information provided with your order. If delivery or supply cannot proceed as agreed, contact us to discuss your order and legal remedies.'],
    ['Your rights and complaints','Nothing in these terms excludes or restricts consumer rights or liabilities that cannot lawfully be excluded. For complaints contact '+complaints+'. Changes to these terms will not retrospectively remove rights under an existing order.'],
  ]),
  page('privacy-policy','Privacy Policy','/policies/privacy-policy','REWRITE',[
    ['Who is responsible',company+'<p>Contact '+support+' with privacy questions or requests. Please do not send payment card details or unnecessary sensitive information.</p>'],
    ['Fabric Intelligence','We process the preferences and room information you provide, colour observations, your palette edits and reactions, recommendations, and consultation identifiers. Automated analysis and recommendation processing help suggest fabrics. You decide what to choose; recommendations do not commit you to an order. Consultation records and related events are stored by the CurtainsUK service so the experience can continue and be supported.'],
    ['Room and reference images','An image is optional and is used only to provide the Fabric Intelligence service you request. We do not use uploaded room images for model training, general AI training, product or model improvement, unrelated evaluation or research, marketing, or a reusable image dataset. Our current consultation database rejects raw image data and stores derived observations and preferences instead. The upstream processor, temporary handling, logs, backups, deletion behaviour and international processing are being verified before precise operational promises are made. Please do not include identifiable people, documents, addresses or other unnecessary personal details. See '+link('/pages/room-image-ai-privacy','Room Image & AI Privacy')+'.'],
    ['Guided Measure','Guided Measure saves entered measurements, setup, progress, earlier readings and confirmed briefs in local storage in your browser. They remain on that device until cleared or replaced by the tool/browser. Confirming a brief does not itself make it a production specification. Measurements you later submit in Make Curtains become part of the order configuration and review record.'],
    ['Samples and made-to-measure orders','We use the contact and delivery details you provide to handle sample orders and curtain orders. Curtain records include the fabric, options, raw measurements, price and review/production history. Payment status and order information are available to us through Shopify. Payment card information is handled by Shopify and the payment service used at checkout; our curtain configuration service does not request full card details.'],
    ['Support, complaints and media','We use your correspondence and relevant order or enquiry information to answer you and handle any problem. Customer support, complaints, media enquiries and order-change requests have separate contact routes. Records may be needed to follow up your case, meet legal obligations or resolve a dispute.'],
    ['Purposes and legal bases','Order fulfilment and steps you request before buying use the contract basis. Applicable accounting and other statutory records use the legal-obligation basis. Service security, fraud prevention and handling routine enquiries may rely on legitimate interests, subject to your rights. Where processing requires consent, including non-exempt optional tracking, consent must be obtained and may be withdrawn.'],
    ['Service providers','Shopify provides the storefront, checkout and related order services. The current CurtainsUK backend uses Vercel for hosting and Supabase for application records, with a separate image/recommendation service. Payment, delivery and manufacturing providers receive information needed for their role. The complete processor list, subprocessors and image-provider arrangements remain subject to technical and contractual verification before this notice is released.'],
    ['Shopify Network Intelligence','Shopify Network Intelligence is enabled in this store. Shopify describes this as using customer data with data from other Shopify merchants to support features including advertising and personalisation. Read '+link('https://www.shopify.com/legal/privacy','Shopify’s Privacy Policy')+' for its processing and rights information.'],
    ['Cookies and browser storage','Read '+link('/pages/cookies-policy','Cookie Information')+' for cookies, local storage and saved choices. Cookie Settings opens the Shopify preferences control once configured. Clearing browser storage can remove a saved consultation or measurement brief; it does not erase order records already submitted to us.'],
    ['Retention and international processing','We must keep information only for the purposes and periods justified by our service and legal obligations. The record-specific retention schedule, processor deletion arrangements and applicable safeguards for international transfers require confirmation. Shopify Admin currently lists the European Union as the primary data-hosting location; this does not prove that every service or transfer is confined to the EU.'],
    ['Your rights','Depending on the circumstances, you can request access, correction, deletion, restriction, portability or object to use of your information. Where consent applies, you can withdraw it. Email '+support+'; we may need to check your identity. You can also raise a concern with the '+link('https://ico.org.uk/make-a-complaint/','Information Commissioner’s Office')+'.'],
  ],['Verify purpose-by-purpose lawful-basis/legitimate-interest record; HCI image processor, temporary handling, logs, backups, training terms and deletion/retention; record retention criteria; processor contracts, subprocessors, countries and transfer safeguards; Shopify Network Intelligence notice requirements; and consent-controlled pixel behaviour.']),
  page('contact-information','Contact information','/policies/contact-information','REWRITE',[
    ['Customer support',support],['Complaints',complaints],['Media & Press',link('mailto:'+contacts.media,contacts.media)],['Made-to-measure changes',changeNotice],['Business details',company],
  ]),
  page('contact-us','Contact Us','/pages/contact-us','REWRITE',[
    ['A little help, at any stage','From choosing a fabric to a question about your order, contact '+support+'. Include an order or consultation reference if you have one.'],['Complaints','For a complaint email '+complaints+' and read '+link('/pages/complaints','how to raise a complaint')+'.'],['Press and collaborations','For editorial, interview and collaboration enquiries contact '+link('mailto:'+contacts.media,contacts.media)+'.'],['Order changes',changeNotice],['Find us',company],
  ]),
  page('cookies-policy','Cookie Information','/pages/cookies-policy','REWRITE',[
    ['Cookies and saved choices','Cookies and related browser storage support checkout, security and continuity between steps. Shopify provides commerce technologies; CurtainsUK also saves some choices in local or session storage. Closing a tab does not necessarily remove local storage.'],
    ['What the current service stores','Guided Measure saves measurements and briefs under curtainsuk.guided-measure.v1. The curtain journey also remembers selected fabric/context and progress. Fabric Intelligence uses a session reference to continue a consultation. These are distinct from records submitted to the server or retained with an order.'],
    ['Analytics and marketing','The intended integrations are Facebook & Instagram, Google & YouTube, Pinterest and TikTok. Shopify Network Intelligence is enabled in the current store. The actual events, cookie durations and whether each non-essential event is blocked before consent must be verified against the deployed consent configuration. A listed integration is not proof that every event fires in every journey.'],
    ['Your choices','Use Cookie Settings to open the actual consent preferences. Before release, the relevant UK experience must provide Accept, Reject, Preferences and withdrawal controls, and optional tracking must honour those choices. Browsing alone is not treated as consent. You can also manage site storage in your browser, but removing it may discard saved measurements or session progress.'],
    ['Further information','See '+privacy+' and '+link('https://www.shopify.com/legal/cookies','Shopify’s cookie information')+'.'],
  ],['Shopify banner is currently not visible in any region and the checkout banner is unchecked. Replace the legacy privacy destination, configure the approved consent controls, and verify Accept/Reject/Preferences/withdrawal plus actual non-essential pixel behaviour and cookie/storage lifetimes.']),
  page('curtain-fabric-colour-guide','Fabric Colour, Shade & Variation','/pages/curtain-fabric-colour-guide','REWRITE',[
    ['See it in your own light','Screens, camera exposure and image processing can change how colour appears. Daylight, lamps and neighbouring wall or furnishing colours can also affect how a fabric looks in your room. Where colour, texture or finish matters, '+link('/pages/samples','order a physical sample')+' and look at it in the room at different times.'],
    ['Texture, weave and direction','A woven surface, raised yarn or nap can catch light differently as it turns or hangs. Some materials have natural irregularities. The relevant characteristics depend on the particular fabric; not every fabric has a nap or natural variation. Ask for product-specific information if you are unsure.'],
    ['Samples and later batches','A small sample cannot show every part of a large pattern or the full effect of folds. Dye batches can differ, so a sample or earlier order should not be treated as a guarantee of an identical later batch. Please ask about a critical match before ordering.'],
    ['Pattern and the finished curtain','Pattern repeat and placement affect what is visible across a panel and through its folds. Photography and educational form studies are not promises of a particular motif position on your order. Ask us to review any essential placement requirement before buying.'],
    ['Fabric Intelligence and colour families','Fabric Intelligence, Fabric Knowledge and colour-family swatches help you compare and describe colour. They are interpretations and screen representations, not calibrated proofs of the physical cloth. A room photograph also reflects its lighting and camera settings.'],
    ['Your rights','This guidance does not excuse faulty goods, an incorrect fabric or goods materially not as described. See '+returns+' or contact '+support+'.'],
  ]),
  page('room-image-ai-privacy','Room Image & AI Privacy','/pages/room-image-ai-privacy','MERGE',[
    ['Before you upload',imageNotice],
    ['How the consultation uses your image','The image and your input are processed by the image/recommendation service to suggest colours and fabrics. You can review and correct the colour interpretation. You can use the questions or browse without uploading an image.'],
    ['Stored consultation information','The CurtainsUK integration rejects raw images from stored consultation state. Derived information can include colour observations, your confirmed palette, answers, reactions, recommendations and an image hash. This code-level protection does not establish the independent retention or training terms of every processor.'],
    ['Questions and rights','Contact '+support+' with your consultation reference where available. Please do not attach the original image again just to request help or deletion. Read the full '+privacy+'.'],
  ],['Verify the actual upstream image processor, temporary storage, logs/backups, deletion/retention contract, subprocessors, countries and transfer safeguards before adding precise operational promises. The approved no-training/no-reuse restriction must remain in force.']),
  page('made-to-measure-orders','Your made-to-measure order','/pages/made-to-measure-orders','CREATE',[
    ['From order to curtain','Order placed and paid → CurtainsUK review → Approved for manufacture → Production/workroom → Delivery. Payment does not automatically approve manufacture or release your order to the workroom.'],
    ['What we review','Your fabric and configuration are recorded together with the measurements and validated price. Workshop-derived manufacturing dimensions are a separate production step. If we need clarification, CurtainsUK will contact you.'],
    ['Want to change something?',changeNotice+' Requests are reviewed and changes are not guaranteed. This request window does not replace statutory rights.'],
    ['Before you pay','A configured curtain is fixed in your cart/checkout. Keep it, or remove it and configure your curtains again. Continue shopping takes you to '+link('/pages/fabric-library?view=browse-fabrics','Browse Fabrics')+' without clearing retained cart items.'],
    ['Help after ordering','Contact '+support+' with your order number. See '+returns+' and '+link('/policies/shipping-policy','Delivery Information')+'.'],
  ]),
  page('complaints','Complaints','/pages/complaints','CREATE',[
    ['Tell us what happened','Email '+complaints+'. Include your name, order/reference number if relevant, what happened, any useful dates and the resolution you would like. Photographs can help with a product issue, but please avoid including unnecessary personal information.'],
    ['How we handle it','We will review the information, ask for clarification if needed, and explain the outcome and any proposed next steps. If you disagree with the response, reply with the points you would like reconsidered.'],
    ['Your rights','This process does not limit your statutory rights or prevent you seeking independent advice. We do not claim membership of an alternative dispute resolution scheme. Privacy concerns can also be raised with the '+link('https://ico.org.uk/make-a-complaint/','ICO')+'.'],
  ]),
  page('media','Media & Press','/pages/media','REWRITE',[
    ['About CurtainsUK','CurtainsUK is an interior-led fabric and made-to-measure curtain service operated by Apex Curtains Ltd. Fabric Intelligence connects room context and customer preferences with fabric selection. Our guides explain how curtain form, measurement and fabric work together.'],
    ['Press enquiries','For editorial enquiries, interviews and commentary contact '+link('mailto:'+contacts.media,contacts.media)+'. Please include your publication, topic, deadline and what you need.'],
    ['Areas of interest','Fabric colour, pattern and texture; curtain form and interiors; choosing and measuring made-to-measure curtains; and the role of guided digital tools in fabric selection.'],
    ['Images and collaborations','Ask about approved images, quotations and relevant editorial or creative collaborations. Sending an enquiry does not confirm availability, permission or a partnership.'],
  ]),
  page('modern-slavery-supply-chain','Modern Slavery & Supply Chain Policy','/pages/modern-slavery-supply-chain','CREATE',[
    ['A policy for review','This proposed policy states that forced labour, slavery, servitude and human trafficking have no place in how CurtainsUK works. It is not presented as a statutory annual modern slavery statement.'],
    ['Supply-chain concerns','Customers, workers and business partners can raise a concern through '+complaints+'. Avoid sharing information that could put somebody at risk. If someone is in immediate danger, contact the emergency services.'],
    ['Evidence and accountability','CurtainsUK works with established UK suppliers and expects supply partners to uphold principles of fair treatment and respect. No supplier audits, certifications or formal training programme are claimed here. The final policy must identify only due diligence and escalation actually operated.'],
  ],['Confirm annual/group turnover, business scope and statutory section 54 applicability; policy owner and adoption; supplier checks/escalation actually operated. £36m threshold alone is not proof of exemption.']),
  page('equality-diversity','Equality, Diversity & Non-Discrimination','/pages/equality-diversity','CREATE',[
    ['Proposed commitment','We propose a policy of respectful, fair treatment of customers, employees, applicants, contractors and suppliers/partners. Decisions should be based on relevant needs and criteria. Unlawful discrimination, harassment and victimisation are unacceptable.'],
    ['Protected characteristics','Applicable UK equality protections include age, disability, gender reassignment, marriage and civil partnership, pregnancy and maternity, race, religion or belief, sex and sexual orientation. How the protections apply depends on the relationship and circumstances.'],
    ['Access and adjustments','If you need a different way to access information or communicate with us, contact '+support+' and explain the help you need. We will consider reasonable adjustments under applicable law.'],
    ['Raise a concern','Contact '+complaints+' about unfair treatment. Employment and supplier processes, responsibility and escalation need to be confirmed as part of policy adoption.'],
  ],['Owner approval/adoption, responsible person and actual employee/applicant/contractor/supplier procedures. Do not imply an existing training or monitoring programme.']),
  page('recycling-waste','Recycling & Waste','/pages/recycling-waste','CREATE',[
    ['Practical information','Waste options depend on the material and the local collection service. Follow any material-specific instructions supplied with your product and check what your local service accepts. Do not assume all textiles, coatings, mixed packaging or hardware can go in household recycling.'],
    ['CurtainsUK practices','Where suitable, fabric offcuts and surplus are reused, including for samples. Suitable surplus material may be donated, and suitable remaining fabric waste is recycled. Cardboard and plastic packaging are recycled. Suitability depends on the material, condition and available route; this is not a zero-waste or universal take-back claim.'],
    ['Electrical items','No electrical take-back or WEEE scheme is promised by this draft. Any obligations and process for electrical products require a separate check against products actually sold.'],
  ],['Confirm the operational route/contractor evidence for each material stream and any relevant electrical product obligations before adding more specific claims.']),
  page('responsible-sourcing','Responsible Sourcing','/pages/responsible-sourcing','CREATE',[
    ['Product facts, clearly attributed','Supplier information about a particular fabric should be attributed to that supplier and checked against that product. It is not evidence that every CurtainsUK product or the whole business has the same environmental or social characteristics.'],
    ['Ask about a specific fabric','For an essential sourcing, material or certification requirement, contact '+support+' with the fabric reference before ordering so the available evidence can be checked.'],
    ['CurtainsUK approach','CurtainsUK works with established UK suppliers and expects supply partners to uphold principles of fair treatment and respect. This is a statement of approach, not a formal audit, certification or supplier-assurance programme.'],
    ['Claims need evidence','This draft makes no general sustainable, eco-friendly, carbon-neutral or certified-supply-chain claim. Product-specific supplier facts must be attributed and checked before publication.'],
  ],['Confirm procurement practices and substantiation/source/date/scope for each product claim. No general Sustainability page until evidence is approved.']),
  page('accessibility','Website Accessibility','/pages/accessibility','CREATE',[
    ['Using the website','We want CurtainsUK to be usable with a keyboard, screen reader and mobile device. The shared footer uses named navigation groups, visible focus and expandable sections on small screens. We are reviewing accessibility across the wider service.'],
    ['If something gets in your way','Email '+support+' with the page address, what you were trying to do, and the browser or assistive technology if you know it. Tell us what alternative format or help would work for you.'],
    ['Current scope','This is an accessibility information page, not a claim of formal WCAG certification. Shopify checkout and third-party services have separate interfaces. We record known issues and improvements rather than claiming that every journey has passed a full accessibility audit.'],
  ]),
  page('shipping-policy','Delivery Information','/policies/shipping-policy','REWRITE',[
    ['Before ordering','CurtainsUK currently delivers to UK Mainland. Check the delivery area, current charge and timing supplied for your order before payment. Samples are delivered free. Samples and made-to-measure curtains are different order types and may travel separately.'],
    ['Made-to-measure curtains','Made-to-measure curtains normally take approximately 3–4 weeks, presented as an estimate rather than an absolute guarantee. Your paid order goes through CurtainsUK review and approval for manufacture before workroom release. Payment alone does not mean your curtains are in production. Contact '+support+' with your order reference for help.'],
    ['Receiving your order','The delivery charge for curtain orders is the current checkout delivery rule and may change; it is shown before payment. If goods arrive damaged, incorrect or incomplete, contact '+support+' as soon as reasonably possible with your order details and useful photographs where appropriate. Read '+returns+'; this guidance does not limit your legal rights.'],
  ]),
  page('fabric-care-guide','Curtain Care & Cleaning','/pages/fabric-care-guide','REWRITE',[
    ['Start with your specific fabric','Use the care information supplied for your chosen fabric and finished curtain. Face fabric, lining, interlining, trims and hardware can have different requirements. A method suitable for one material may not suit the complete curtain.'],
    ['Before cleaning','Check the supplied label or ask '+support+' with your order/fabric reference. Do not assume a curtain is washable, suitable for tumble drying or suitable for a particular solvent. Seek specialist curtain-cleaning advice if the instructions are unclear.'],
    ['Looking after the surface','Consider '+colour+' when assessing nap, weave, shade or surface changes. Report damage or a suspected fault through '+returns+'.'],
  ]),
  page('faq-1','FAQs','/pages/faq-1','REWRITE',[
    ['How do I measure?','Use '+link('/pages/how-to-measure','Guided Measure')+' with your track or pole already fitted. It shows the correct tape anchors for your setup. If unsure, pause and contact us.'],
    ['Can I try the fabric?','Order a '+link('/pages/samples','£2.50 fabric sample')+' from an eligible fabric in Browse Fabrics, Fabric Detail or Fabric Intelligence. A sample helps you judge the surface and colour in your room.'],
    ['Can I edit a curtain in my cart?','No. Keep the configured curtain or remove it and configure again. This keeps fabric, measurements and price together. Continue shopping returns to '+link('/pages/fabric-library?view=browse-fabrics','Browse Fabrics')+' without clearing retained items.'],
    ['What happens after payment?','Your made-to-measure order goes to CurtainsUK review. Approval and workroom release are separate staff actions. Read '+link('/pages/made-to-measure-orders','Your made-to-measure order')+'.'],
    ['How do I request a change?',changeNotice],
    ['Can I return my order?','The rules differ for samples, made-to-measure goods and goods with a problem. See '+returns+'.'],
  ]),
  page('about-us-1','About CurtainsUK','/pages/about-us-1','REWRITE',[
    ['Fabric first','CurtainsUK is an interior-led fabric specialist and made-to-measure curtain service. Begin with your room, choose your fabric, explore curtain form, measure and make.'],
    ['Guidance that connects the choices','Fabric Intelligence helps relate fabric to your room. Fabric Knowledge explains colour, pattern, activity, texture, finish, character and presence. Curtain Style and Guided Measure help turn those choices into a considered curtain configuration.'],
    ['Here to help','Contact '+support+' for customer support. CurtainsUK is operated by Apex Curtains Ltd.'],
  ]),
];
export const aliases = {
  '/pages/privacy-policy':'/policies/privacy-policy',
  '/pages/terms-and-conditions':'/policies/terms-of-service',
  '/pages/faq':'/pages/faq-1',
  '/pages/about-us':'/pages/about-us-1',
  '/apps/curtainsuk-decision/image-privacy':'/pages/room-image-ai-privacy',
  '/pages/curtain-measuring-guide':'/pages/how-to-measure',
  '/pages/how-to-measure-for-curtains':'/pages/how-to-measure',
  '/pages/curtain-installation-guide':'/pages/how-to-fit',
};
