import type { Metadata } from "next";
import { Ruler, TriangleAlert } from "lucide-react";
import TrackedLink from "@/components/analytics/TrackedLink";

export const metadata: Metadata = { title: "How to Measure for Curtains", description: "Measure track or usable pole width and finished curtain drop in centimetres, with specialist guidance for shaped windows." };

export default function MeasurePage() {
  return <main className="bg-[#f7f3ec] px-4 py-16 text-[#173c32] sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto max-w-4xl"><div className="text-xs font-semibold uppercase tracking-[0.18em] text-[#996a31]">Measurement guide</div><h1 className="mt-4 text-4xl font-semibold tracking-[-0.05em] sm:text-6xl">Measure the space the curtains must cover</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[#587168]">Use centimetres. For a normal window, enter the complete track width or usable pole width and the finished drop—never the width of an existing curtain.</p><div className="mt-10 grid gap-5 md:grid-cols-2"><article className="rounded-3xl bg-white p-7"><Ruler className="h-6 w-6 text-[#a36d2d]" /><h2 className="mt-5 text-xl font-semibold">Rectangular windows and doors</h2><ol className="mt-4 space-y-3 text-sm leading-6 text-[#5a7169]"><li>1. Choose TRACK_WIDTH or POLE_USABLE_WIDTH.</li><li>2. Measure the complete usable width.</li><li>3. Measure from the intended heading position to the finished hem.</li><li>4. Repeat every measurement before continuing.</li></ol></article><article className="rounded-3xl bg-[#173c32] p-7 text-white"><TriangleAlert className="h-6 w-6 text-[#e2bc82]" /><h2 className="mt-5 text-xl font-semibold">Apex, triangular and gable</h2><p className="mt-4 text-sm leading-6 text-white/70">You will need base width, peak height, both verticals, both slopes, fixing position, opening direction and photographs. These jobs always stop for technical approval.</p></article></div><TrackedLink href="/shop-by-window" eventName="window_type_selected" eventData={{ placement: "measure_guide" }} className="mt-9 inline-flex rounded-full bg-[#173c32] px-6 py-3.5 text-sm font-semibold text-white">Choose my window type</TrackedLink></div></main>;
}
