import { DISCOVERY_ROUTES, orderedDiscoveryRoutes, type DiscoveryRoute } from "./portal-discovery";

export const PORTAL_MAP_VERSION = "supplier-portals-2026-09-08-v2";
export interface PortalRecipe {
  location: string; status: "OBSERVED" | "PARTIALLY_OBSERVED" | "ACCESS_BLOCKED";
  steps: string[];
}
// Only observed entry points. Follow links present in the page; never manufacture a product URL.
// Capability links and login/session data deliberately have no representation here.
export const PORTAL_DISCOVERY_MAPS: Record<string, Record<DiscoveryRoute, PortalRecipe>> = {
  "sanderson-design-group": {
    EXACT_PRODUCT: {location:"sdg.product",status:"OBSERVED",steps:["Open a previously verified portal product link; compare displayed SKU, brand, design and Colour Variant.","Product slug identifier can differ from the displayed SKU: F1787/01 is CCF0795-01. Keep both identities; do not replace the master SKU."]},
    SKU_SEARCH: {location:"sdg.search",status:"OBSERVED",steps:["Fill textbox 'What are you looking for?' with exact SKU; click button 'Search'.","Read every result identity and product type. DARP222519 returned DARP222529: reject this result.","Use 'Viewing N of N' and 'View more' to exhaust pagination; preserve page progress."]},
    DESIGN: {location:"sdg.design",status:"PARTIALLY_OBSERVED",steps:["Search the exact design using the same search control; inspect exact matches only.","Follow any design links actually exposed by matched products. Search results are not identity evidence."]},
    COLOURWAY: {location:"sdg.variants",status:"OBSERVED",steps:["Inspect Colour Variant buttons on the product page; open the target variant and re-read SKU and colour.","Other variants' image URLs are present in the DOM. Never collect the entire page as one colourway gallery."]},
    COLLECTION: {location:"sdg.collection",status:"PARTIALLY_OBSERVED",steps:["Use /all-brands and the selected brand, then follow collection links actually shown.","Cross-check collection in Product Details; collection-name similarity does not prove a colourway. Zoffany brand cards explicitly pair ZOF0223-02 with legacy image SKU ZINF322785, and ZOF0236-04 with ZINF322800. Exact brand/design/colour also agree. Record each verified identifier pair; never invent a conversion formula or accept a name-only match."]},
    FABRIC_LISTING: {location:"sdg.fabric-listing",status:"OBSERVED",steps:["PRIMARY exact-colourway source for all six SDG brands: search the authenticated fabric/collection listings by exact SKU, or collect a bounded prefix/collection set and reconcile every displayed SKU exactly. Retain actual product links and displayed identity. Open the product only if a better image is needed.","Each product-inline card associates brand, design/colour title, displayed SKU, lifecycle label and fabric/product type with its image. Read only these fields, not the card's commercial values.","CCF, F179, F180 and F181 searches expose current master candidates in groups; reconcile exact SKU, brand and colour before importing. Some CCF product slugs still display legacy F SKUs.","Images are observed under /static/media/catalog/product/ and may be 1366px square. Preserve the actual filename; never manufacture hash suffixes.","Exclude wallpaper and explicitly discontinued products. Pair It With includes wallpaper. Unmatched master SKUs stay unresolved."]},
    GALLERY: {location:"sdg.gallery",status:"PARTIALLY_OBSERVED",steps:["Inspect images and any gallery controls associated with the selected product.","Exclude Key Details corporate images, Pair It With recommendations, and unselected variants.","Filecamp is optional for additional room/lifestyle/design media. Its separate login never blocks importing a verified trade-listing colourway image."]},
    LIFESTYLE: {location:"sdg.lifestyle",status:"PARTIALLY_OBSERVED",steps:["Inspect design/collection galleries and their digital design books for captions identifying room imagery.","Design-level associations may produce ROOM only. If colour is not established, never use as MAIN/SWATCH."]},
    RESOURCES: {location:"sdg.resources",status:"PARTIALLY_OBSERVED",steps:["Open /document-browser: General Documents > 4. New Collection Details and 5. Digital Design Books > exact brand.","Observed PDF counts: Clarke & Clarke 19, Harlequin 25, Morris & Co 17, Sanderson 19, Scion 15, Zoffany 13. These include wallpaper books and are not all fabric evidence.","Collection books include Expressions Fabric, Elements, Wild Escape Indoor Outdoor, Wardle Velvets and other collection names. Inspect captions before associating ROOM media; filenames alone establish only collection context.","The PDF controls opened a browser-policy-blocked document preview; contents remain uninspected. Do not work around the blocked preview.","Follow portal menu File Camp Media Store to clarkeandclarke.filecamp.com; do not persist its capability link. Separate login currently blocks inspection.","This optional additional-media route is not exhausted until document folders and the media store have been checked. It is never a prerequisite for exact-colourway import. Keep unmapped distinct from unavailable, and require an authenticated exact-SKU listing search before any missing-image conclusion."]},
    DESIGN_COLOUR_SEARCH: {location:"sdg.design-colour-search",status:"PARTIALLY_OBSERVED",steps:["Search exact design plus exact colour using the global search. Check all result pages.","Accept only exact brand/design/colour with fabric identity and an explicit relationship to this image; record ambiguity otherwise."]},
  },
  "prestigious-textiles": {
    EXACT_PRODUCT: {location:"pt.product",status:"OBSERVED",steps:["Authorised Webtex is accessible. Use verified collection/product links and compare Product Code, collection, design and colour.","A collection colourway opens iframe ifrModal. Read the exact product identity and full-size image element; exclude adjacent prices and stock from media observations.","Dali Mocha 4270/147 exposes a 1400x1400 full-size file under prestigiousonline.co.uk/images/images/4270 dali/ with SKU, design and colour in the filename. Use each observed URL; do not infer another product's path.","Never persist the Webtex session fragment or authentication state."]},
    SKU_SEARCH: {location:"pt.search",status:"PARTIALLY_OBSERVED",steps:["The authenticated navigation exposes Stock Enquiry and Collection Enquiry; inspect exact-SKU search results before marking this route exhausted.","Public /fabric-search has Filter by Fabric and Go, but the observed query did not narrow results. Do not treat unchanged listings as no exact result."]},
    DESIGN: {location:"pt.design",status:"OBSERVED",steps:["Follow the product's actual /fabrics/collection/design/ breadcrumb; inspect exact design colourways and media."]},
    COLOURWAY: {location:"pt.colourway",status:"OBSERVED",steps:["Follow actual /product/ links from design/collection pages and validate the full Product Code.","Keep genuine thumbnails if these are the usable supplier copy; do not invent high-resolution URLs."]},
    COLLECTION: {location:"pt.collection",status:"OBSERVED",steps:["Use /fabrics and actual collection links; inspect collection hero/gallery and links to designs.","Collection-only imagery is ADDITIONAL context, never an exact colourway MAIN."]},
    FABRIC_LISTING: {location:"pt.fabric-listing",status:"OBSERVED",steps:["Webtex Collection Enquiry lists 384 collections, including non-fabric ranges. Formation exposes 32 colourways across seven designs.","Colourway link attributes contain stable product codes; collect the code with the visible design/colour and image from the same entry. Follow UI controls normally, never execute extracted JavaScript links.","Use /fabric-search/ and public collection lists as additional sources. Retain observed links, not guessed slugs; a non-working filter leaves discovery incomplete."]},
    GALLERY: {location:"pt.gallery",status:"PARTIALLY_OBSERVED",steps:["Inspect actual product/design/collection image elements and gallery links.","Product images appear under /wp-content/uploads/product_images/, including /thumbs/. Record each source location."]},
    LIFESTYLE: {location:"pt.lifestyle",status:"PARTIALLY_OBSERVED",steps:["Prestigious SharePoint Public > Lifestyle Imagery > Images is accessible and organised into 22 seasonal/contract folders, then collection folders, then JPEGs.","MINIMALIST has 12 JPEGs, including CAM 1 through CAM 11 and a MAIN file. Filenames alone identify the collection, not a design or colourway.","Read captions/file details or a corresponding brochure before assigning design ROOM media. Collection-only imagery remains ADDITIONAL and cannot activate an exact colourway.","Wait for the correct named folder grid after navigation. SharePoint folder activation can lag; re-observe instead of issuing blind bulk clicks."]},
    RESOURCES: {location:"pt.resources",status:"PARTIALLY_OBSERVED",steps:["Authenticated Webtex Imagery links to the authorised SharePoint library and brochure resources. Do not copy displayed passwords, shared access links or session parameters into records.","Use /brochures: seasonal collection brochures are listed from 2021 through Autumn/Winter 2026.","Library structure is mapped, but individual collection files and captions still require inspection. Do not mark a fabric's resources exhausted from a folder listing alone."]},
    DESIGN_COLOUR_SEARCH: {location:"pt.design-colour-search",status:"PARTIALLY_OBSERVED",steps:["Use exact design plus colour in the authorised search, confirming results actually changed.","Validate exact design/colour and stable product identity; do not accept merely similar names."]},
  },
};
export function portalDiscoveryPlan(supplier: string, remaining: readonly DiscoveryRoute[] = DISCOVERY_ROUTES) {
  const map = PORTAL_DISCOVERY_MAPS[supplier];
  if (!map) throw new Error("PORTAL_MAP_NOT_AVAILABLE");
  return orderedDiscoveryRoutes(supplier).filter(route => remaining.includes(route)).map(route => ({route,...map[route]}));
}
