const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const cp = require('node:child_process');
const assert = require('node:assert/strict');
const theme = 'shopify-theme/curtainsuk-dawn-16/';
const parse = text => JSON.parse(text.slice(text.indexOf('{')));
const before = parse(cp.execFileSync('git', ['show', '764257662d91dc39cca537650623c8a06130bb35:' + theme + 'locales/en.default.json'], { encoding: 'utf8' }));
const after = parse(fs.readFileSync(theme + 'locales/en.default.json', 'utf8'));
delete before.homepage_studio;
delete after.homepage_studio;
assert.deepEqual(after, before);
const allFindings = JSON.parse(fs.readFileSync(path.join(__dirname, 'theme-check.json'), 'utf8').replace(/^\uFEFF/, ''));
const changedFindings = allFindings.filter(f => /curtainsuk-home-studio\.(liquid|css|js)$|locales[\\/]en.default.json$|templates[\\/]index.json$/.test(f.path));
assert.equal(changedFindings.length, 0);
const files = ['templates/index.json','locales/en.default.json','sections/curtainsuk-home-studio.liquid','assets/curtainsuk-home-studio.css','assets/curtainsuk-home-studio.js','assets/cuk-home-room-inspiration.webp',...['wave','double-pinch','pencil-pleat','eyelet'].map(x=>`assets/cuk-home-heading-${x}.webp`),...['living','bedroom','lounge','office'].flatMap(room=>['daylight','evening'].map(mode=>`assets/cuk-home-${room}-${mode}.webp`))];
const result = { at:new Date().toISOString(),source:cp.execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),nonHomepageTranslationsPreserved:true,changedThemeFilesWithoutFindings:true,unrelatedThemeFilesWithFindings:allFindings.length,files:files.map(filename=>{const raw=fs.readFileSync(theme+filename);const content=/\.(liquid|css|js|json)$/.test(filename)?Buffer.from(raw.toString('utf8').replace(/\r\n/g,'\n')):raw;return {filename,bytes:content.length,md5:crypto.createHash('md5').update(content).digest('hex')};})};
fs.writeFileSync(path.join(__dirname,'source-check.json'),JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify(result));
